# Generated by Django 2.2.1 on 2019-05-11 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailycrashreport',
            old_name='no_of_crashes',
            new_name='noofcrashes',
        ),
        migrations.RenameField(
            model_name='dailycrashreport',
            old_name='reportDate',
            new_name='reportdate',
        ),
        migrations.RenameField(
            model_name='dailycrashreport',
            old_name='reportTime',
            new_name='reporttime',
        ),
    ]
